// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzdrxmvrtjkrvieyetkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZHJ4bXZydGprcnZpZXlldGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTY2NjYsImV4cCI6MjA3MjEzMjY2Nn0.BZCRpT6P1ttIJijZzwS_xA6hVMIVJhrwSJCx7AQk1F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});